### ISSUE TITLE
possibly outdated formatter

### ISSUE THREAD

**Issue by chdoc** [E5DR/talon_german#3]
With an up to date community repository, I also needed to make the following change in order get "groß geschrieben" to work:
```
 großgeschrieben | mach groß:
     edit.select_word()
-    user.formatters_reformat_selection("title")
+    user.formatters_reformat_selection("CAPITALIZE_ALL_WORDS")
```
It may be preferable to only select the current word if there isn't already a selection.

**Comment by E5DR** [comment]
Fixed in 5d96682dcc3cbf9324be73c11a8db5bb355198af.

Checking for an existing selection seems useful and is what a user would expect, I also thought about it.

What comes to my mind is to try and copy to see if we get text in the clipboard, but too many editors have some convenience feature that will copy the whole line if nothing is selected - so this method does not seem too reliable.
So far I myself never really ran into that case during my day-to-day usage, so I just left it as it was.

Do you have an idea for a reliable way?
