### ISSUE TITLE
Remove default `user.context_sensitive_dictation = 1`

### ISSUE THREAD

**Issue by chdoc** [E5DR/talon_german#4]
I think that `user.context_sensitive_dictation = 1` is an absolutely atrocious default. Whether context sensitive dictation works for an application or not, is pretty much independent of German mode. I just spent the better part of an hour trying to understand why my `user.context_sensitive_dictation = false` was being ignored, before realizing that it wasn't ignored in English dictation mode - which I have never used except for testing this.

**Comment by E5DR** [comment]
I think are right with this, thanks for bringing this to my notice.
Since german dictation is now no different from english dictation, this repo should not change the established behaviour just because the language is different.

How this came to be is that the old vosk branch originally had its own implementation with a separate setting, and when I recently switched to the community implementation I just moved over the setting as well.
Also be aware that this branch is still a bit of a work in progress.

On a different note, if you happened to deactivate context sensitive dictation because there is some specific application or website that does not play well with it (for example slack, vim, word), note that you can apply this setting on a per-context basis.
So you could enable it globally and just deactivate it for individual troublesome applications, or have it disabled by default and enable it for known good applications. In my experience this is more convenient than simply deactivating the feature everywhere.
There is also the option of overwriting `dictation_peek()` to adjust for application specific behavior.

**Comment by chdoc** [comment]
> Also be aware that this branch is still a bit of a work in progress.

You keep repeating yourself. I am well aware that this was all work in progress. This is why I am trying to help this make progress.

> So you could enable it globally and just deactivate it for individual troublesome applications, or have it disabled by default and enable it for known good applications.

I am aware of this, and I am following the latter approach. For the time being, I am only using dictation with `emacs` and `libreoffice`, and my personal `emacs.talon` already contains. 
```
settings():
    user.context_sensitive_dictation = true
```
